In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import pickle
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from ydata_profiling import ProfileReport
from scipy.stats.mstats import winsorize
from scipy.stats import boxcox
from sklearn.model_selection import train_test_split


In [2]:
from hello1 import *

In [3]:
data=pd.read_csv('HR.csv')

In [4]:
data.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [5]:
data.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [42]:
data.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

In [66]:
data.Attrition.unique()

array([1, 0])

In [67]:
data['Attrition']=data['Attrition'].replace({'Yes':1,'No':0})

In [68]:
with open("preprocessor2.pkl","rb") as f:
    preprocessor=pickle.load(f)

In [69]:
preprocessor

ColumnTransformer(transformers=[('OHE_columns', OneHotEncoder(),
                                 ['BusinessTravel', 'Department',
                                  'MaritalStatus', 'EducationField', 'Gender',
                                  'JobRole']),
                                ('standard_scaler', StandardScaler(),
                                 ['Age', 'DailyRate', 'DistanceFromHome',
                                  'MonthlyRate', 'HourlyRate',
                                  'NumCompaniesWorked', 'TotalWorkingYears',
                                  'TrainingTimesLastYear', 'YearsAtCompany',
                                  'YearsInCurrentRole...
                                  'PercentSalaryHike']),
                                ('label_encoder', ModifiedLabelEncoder(),
                                 ['OverTime']),
                                ('passthrough',
                                 FunctionTransformer(func=<function same at 0x00000267404E96C0>),
                                 ['Education', 'EnvironmentSatisfaction',
                                  'JobInvolvement', 'JobLevel',
                                  'JobSatisfaction', 'PercentSalaryHike',
                                  'RelationshipSatisfaction',
                                  'StockOptionLevel', 'TrainingTimesLastYear',
                                  'WorkLifeBalance', 'PerformanceRating'])])

In [70]:
x=data.drop(['Attrition'],axis=1)
y=data['Attrition']

In [71]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [72]:
len(x_train)

1176

In [73]:
len(y_train)

1176

In [74]:
len(y)

1470

In [75]:
preprocessor.fit(x_train)

ColumnTransformer(transformers=[('OHE_columns', OneHotEncoder(),
                                 ['BusinessTravel', 'Department',
                                  'MaritalStatus', 'EducationField', 'Gender',
                                  'JobRole']),
                                ('standard_scaler', StandardScaler(),
                                 ['Age', 'DailyRate', 'DistanceFromHome',
                                  'MonthlyRate', 'HourlyRate',
                                  'NumCompaniesWorked', 'TotalWorkingYears',
                                  'TrainingTimesLastYear', 'YearsAtCompany',
                                  'YearsInCurrentRole...
                                  'PercentSalaryHike']),
                                ('label_encoder', ModifiedLabelEncoder(),
                                 ['OverTime']),
                                ('passthrough',
                                 FunctionTransformer(func=<function same at 0x00000267404E96C0>),
                                 ['Education', 'EnvironmentSatisfaction',
                                  'JobInvolvement', 'JobLevel',
                                  'JobSatisfaction', 'PercentSalaryHike',
                                  'RelationshipSatisfaction',
                                  'StockOptionLevel', 'TrainingTimesLastYear',
                                  'WorkLifeBalance', 'PerformanceRating'])])

In [76]:
processed_data_x=preprocessor.transform(x_train)

In [77]:
processed_data_x

array([[0., 0., 1., ..., 3., 3., 3.],
       [1., 0., 0., ..., 2., 3., 3.],
       [0., 0., 1., ..., 2., 3., 3.],
       ...,
       [0., 1., 0., ..., 5., 3., 3.],
       [0., 0., 1., ..., 2., 3., 3.],
       [0., 0., 1., ..., 2., 3., 3.]])

In [56]:
y_train=data['Attrition'].replace({'Yes':1,'No':0})

In [26]:
y_test=data['Attrition'].replace({'Yes':1,'No':0})

In [78]:
processed_data_y=preprocessor.transform(x_test)

In [79]:
processed_data_y

array([[0., 0., 1., ..., 4., 3., 3.],
       [0., 0., 1., ..., 3., 3., 3.],
       [0., 0., 1., ..., 2., 3., 3.],
       ...,
       [0., 0., 1., ..., 2., 3., 3.],
       [0., 0., 1., ..., 2., 3., 3.],
       [0., 0., 1., ..., 2., 3., 4.]])

In [80]:
y_train

1097    0
727     0
254     0
1175    0
1341    0
       ..
1130    0
1294    0
860     1
1459    0
1126    0
Name: Attrition, Length: 1176, dtype: int64

In [81]:
y_test

1041    0
184     0
1222    1
67      0
220     0
       ..
567     0
560     0
945     0
522     0
651     0
Name: Attrition, Length: 294, dtype: int64

In [82]:
from imblearn.over_sampling import SMOTE

In [83]:
sm=SMOTE()

In [84]:
len(processed_data_x)

1176

In [85]:
len(y_train)

1176

In [86]:
x_sm,y_sm=sm.fit_resample(processed_data_x,y_train)

In [89]:
print(len(x_sm))

1956


In [91]:
print(len(y_sm))

1956


DECISION TREE CLASSIFIER

In [92]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_sm,y_sm)

DecisionTreeClassifier()

In [96]:
y_pred=dt.predict(processed_data_y)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0])

In [97]:
from sklearn.metrics import classification_report

In [101]:
report=classification_report(y_pred,y_test)
print(report)

              precision    recall  f1-score   support

           0       0.86      0.88      0.87       249
           1       0.26      0.22      0.24        45

    accuracy                           0.78       294
   macro avg       0.56      0.55      0.56       294
weighted avg       0.77      0.78      0.78       294



In [102]:
from sklearn.model_selection import GridSearchCV

In [112]:
params={
    'criterion':('gini','entropy'),
    'splitter':('best','random'),
    'max_depth':(list(range(1,20))),
    'min_samples_split':[2,3,4],
    'min_samples_leaf':list(range(1,20)),
}

In [113]:
model=DecisionTreeClassifier()

In [114]:
grid=GridSearchCV(model,params,scoring='f1',n_jobs=-1,verbose=1,cv=3)

In [115]:
grid.fit(x_sm,y_sm)

Fitting 3 folds for each of 4332 candidates, totalling 12996 fits


GridSearchCV(cv=3, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ('gini', 'entropy'),
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                       13, 14, 15, 16, 17, 18, 19],
                         'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                              12, 13, 14, 15, 16, 17, 18, 19],
                         'min_samples_split': [2, 3, 4],
                         'splitter': ('best', 'random')},
             scoring='f1', verbose=1)

In [116]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_depth': 16, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'random'}


In [117]:
model1=DecisionTreeClassifier(criterion='entropy', max_depth=16, min_samples_leaf= 1, min_samples_split= 2, splitter='random')

In [119]:
model1.fit(x_sm,y_sm)

DecisionTreeClassifier(criterion='entropy', max_depth=16, splitter='random')

In [122]:
y_pred1=model1.predict(processed_data_y)
y_pred1

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0])

In [124]:
from sklearn.metrics import classification_report
report1=classification_report(y_pred1,y_test)
print(report1)

              precision    recall  f1-score   support

           0       0.86      0.88      0.87       248
           1       0.26      0.22      0.24        46

    accuracy                           0.78       294
   macro avg       0.56      0.55      0.55       294
weighted avg       0.76      0.78      0.77       294



RANDOM FOREST

In [126]:
from sklearn.ensemble import RandomForestClassifier

In [127]:
a=RandomForestClassifier(n_estimators=100)

In [128]:
a.fit(x_sm,y_sm)

RandomForestClassifier()

In [129]:
y_pred_a=a.predict(processed_data_y)

In [130]:
report3=classification_report(y_pred_a,y_test)
print(report3)

              precision    recall  f1-score   support

           0       0.98      0.88      0.93       284
           1       0.15      0.60      0.24        10

    accuracy                           0.87       294
   macro avg       0.57      0.74      0.59       294
weighted avg       0.96      0.87      0.91       294



In [131]:
from sklearn.model_selection import RandomizedSearchCV

In [132]:
n_estimators=[int(x) for x in np.linspace(start=200,stop=2000,num=10)]
max_features=['auto','sqrt']
max_depth=[int(x) for x in np.linspace(10,110,num=11)]
max_depth.append(None)
min_samples_split=[2,5,10]
min_samples_leaf=[1,2,4]


In [133]:
random_grid={'n_estimators':n_estimators,'max_features':max_features,'max_depth':max_depth,
             'min_samples_split':min_samples_split,'min_samples_leaf':min_samples_leaf}

In [135]:
model5=RandomForestClassifier(random_state=42)

In [136]:
grid=RandomizedSearchCV(model5,param_distributions=random_grid,scoring='f1',verbose=1,n_jobs=-1,n_iter=100,
                       cv=3,random_state=42)

In [137]:
grid.fit(x_sm,y_sm)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=42, scoring='f1', verbose=1)

In [139]:
print(grid.best_params_)

{'n_estimators': 800, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': None}


In [140]:
rfc=RandomForestClassifier(n_estimators= 800, min_samples_split= 2, min_samples_leaf= 1, max_features= 'sqrt', max_depth= None)

In [141]:
rfc.fit(x_sm,y_sm)

RandomForestClassifier(n_estimators=800)

In [142]:
y_predict_rfc=rfc.predict(processed_data_y)

In [143]:
report_rfc=classification_report(y_predict_rfc,y_test)
print(report_rfc)

              precision    recall  f1-score   support

           0       0.98      0.88      0.93       285
           1       0.13      0.56      0.21         9

    accuracy                           0.87       294
   macro avg       0.56      0.72      0.57       294
weighted avg       0.96      0.87      0.91       294



BAGGING

In [145]:
from sklearn.neighbors import KNeighborsClassifier

In [146]:
KNN1=KNeighborsClassifier()

In [147]:
KNN1.fit(x_sm,y_sm)

KNeighborsClassifier()

In [148]:
y_pred=KNN1.predict(processed_data_y)
y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0])

In [149]:
report_knn=classification_report(y_pred,y_test)
print(report_knn)

              precision    recall  f1-score   support

           0       0.55      0.91      0.68       154
           1       0.64      0.18      0.28       140

    accuracy                           0.56       294
   macro avg       0.60      0.54      0.48       294
weighted avg       0.59      0.56      0.49       294



In [150]:
from sklearn.ensemble import BaggingClassifier

In [152]:
model_bag=BaggingClassifier(estimator=KNN1,n_estimators=500,max_samples=0.5,max_features=0.75)

In [153]:
model_bag.fit(x_sm,y_sm)

BaggingClassifier(estimator=KNeighborsClassifier(), max_features=0.75,
                  max_samples=0.5, n_estimators=500)

In [154]:
y_predict_bag=model_bag.predict(processed_data_y)

In [155]:
report_bag=classification_report(y_predict_bag,y_test)
print(report_bag)

              precision    recall  f1-score   support

           0       0.57      0.92      0.71       158
           1       0.69      0.20      0.31       136

    accuracy                           0.59       294
   macro avg       0.63      0.56      0.51       294
weighted avg       0.63      0.59      0.52       294



BOOSTING

GRADIENT BOOSTING

In [157]:
from sklearn.ensemble import GradientBoostingClassifier

In [158]:
gbc=GradientBoostingClassifier()
gbc.fit(x_sm,y_sm)
pred=gbc.predict(processed_data_y)

In [159]:
report_gb=classification_report(pred,y_test)
print(report_gb)

              precision    recall  f1-score   support

           0       0.97      0.91      0.94       274
           1       0.33      0.65      0.44        20

    accuracy                           0.89       294
   macro avg       0.65      0.78      0.69       294
weighted avg       0.93      0.89      0.90       294



X GRADIENT BOOST

In [169]:
!pip install xgboost

   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.5/72.0 MB 3.4 MB/s eta 0:00:21
   - -------------------------------------- 2.1/72.0 MB 4.7 MB/s eta 0:00:15
   - -------------------------------------- 2.9/72.0 MB 4.6 MB/s eta 0:00:16
   -- ------------------------------------- 3.7/72.0 MB 4.3 MB/s eta 0:00:16
   -- ------------------------------------- 5.0/72.0 MB 4.8 MB/s eta 0:00:15
   --- ------------------------------------ 6.3/72.0 MB 5.1 MB/s eta 0:00:13
   ---- ----------------------------------- 7.6/72.0 MB 5.2 MB/s eta 0:00:13
   ----- ---------------------------------- 9.2/72.0 MB 5.4 MB/s eta 0:00:12
   ----- ---------------------------------- 10.7/72.0 MB 5.6 MB/s eta 0:00:11
   ------ --------------------------------- 12.3/72.0 MB 5.9 MB/s eta 0:00:11
   ------- -------------------------------- 14.2/72.0 MB 6.1 MB/s eta 0:00:10
   -------- ------------------------------- 15.5/72.0 MB 6.2 MB/s eta 0:00:10
  

In [171]:
from xgboost import XGBClassifier

In [174]:
xgb_r= XGBClassifier() ## object creation
xgb_r.fit(x_sm,y_sm)# fitting the data
y_hat=xgb_r.predict(processed_data_y)#predicting the price

# testing score:
report0=classification_report(y_test,y_hat) 
print(report0)

              precision    recall  f1-score   support

           0       0.91      0.96      0.94       255
           1       0.61      0.36      0.45        39

    accuracy                           0.88       294
   macro avg       0.76      0.66      0.69       294
weighted avg       0.87      0.88      0.87       294



In [175]:
params={
    'n_estimators':[100,200,300],
    'learning_rate':[0.01,0.05,0.1],
    'max_depth':[3,4,5],
    'min_child_weight':[5,6,7,8],
    'gamma':[0,0.1,0.2]
}



In [176]:
from sklearn.model_selection import GridSearchCV

In [177]:
model_xgb=XGBClassifier()

In [178]:
grid=GridSearchCV(model_xgb,params,scoring='f1',verbose=1,cv=3)

In [179]:
grid.fit(x_sm,y_sm)

Fitting 3 folds for each of 324 candidates, totalling 972 fits


GridSearchCV(cv=3,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=Non...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             param_grid={'gamma': [0, 0.1, 0.2],
                         'learning_rate': [0.01, 0.05, 0.1],
                         'max_depth': [3, 4, 5],
                         'min_child_weight': [5, 6, 7, 8],
                         'n_estimators': [100, 200, 300]},
             scoring='f1', verbose=1)

In [180]:
print(grid.best_params_)

{'gamma': 0.1, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 300}


In [181]:
xgb=XGBClassifier(gamma= 0.1, learning_rate= 0.01, max_depth= 5, min_child_weight= 6, n_estimators= 300)

In [182]:
xgb.fit(x_sm,y_sm)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=0.1, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.01, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=6, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [183]:
model56=xgb.predict(processed_data_y)

In [186]:
report_xgb=classification_report(model56,y_test)
print(report_xgb)

              precision    recall  f1-score   support

           0       0.96      0.89      0.92       274
           1       0.23      0.45      0.31        20

    accuracy                           0.86       294
   macro avg       0.59      0.67      0.61       294
weighted avg       0.91      0.86      0.88       294

